# Generated by Django 4.2 on 2023-04-10 15:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50)),
                ('ishin_bosh', models.CharField(max_length=15)),
                ('ishin_tush', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('muallif_n', models.CharField(blank=True, max_length=50)),
                ('name', models.CharField(blank=True, max_length=60)),
                ('saxifa', models.SmallIntegerField()),
                ('janr', models.CharField(blank=True, max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=30)),
                ('bituruvchi', models.BooleanField(default=False, verbose_name='bituruvchu')),
                ('ol_kitob', models.SmallIntegerField(default=0, verbose_name='olgan kitoblari soni')),
                ('kursi', models.CharField(choices=[('1 kurs', '1 kurs'), ('2 kurs', '2 kurs'), ('3 kurs', '3 kurs'), ('4 kurs', '4 kurs')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('olinan_sana', models.DateTimeField(auto_now_add=True)),
                ('qaytarilgan_sana', models.DateTimeField(auto_now_add=True)),
                ('qaytardi', models.BooleanField(default=True, verbose_name='qaytaridi')),
                ('kitob_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kutbxona_app.book')),
                ('talab_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kutbxona_app.student')),
            ],
        ),
        migrations.CreateModel(
            name='Muallif',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('muallif_n', models.CharField(max_length=32)),
                ('hayot', models.BooleanField(default=True, verbose_name='hayot')),
                ('jinsi', models.BooleanField(default=True, verbose_name='erkak')),
                ('tugulan_sana', models.DateField()),
                ('kitoblar_soni', models.SmallIntegerField()),
                ('yosh', models.SmallIntegerField(verbose_name='nechi yoshda vafot etani yoki nechi yosh')),
                ('kitoblar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kutbxona_app.book')),
            ],
        ),
    ]
